---
title: "opendatabio:reading"
author: "A. Chalom"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Reading data using the OpenDataBio R client}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---
# Reading data using the OpenDataBio R client

The `opendatabio` R package was created to allow data from an OpenDataBio server to be read, 
and to allow data to be easily imported to an OpenDataBio server. This vignette focus on 
extracting and manipulating data from an OpenDataBio server.

# Setting up the connection

The first thing to do when starting the data import is to correctly set up the connection to
the OpenDataBio server using the `odb_config()` function. The most important parameters for
this function are `base_url`, which should point to the API url for your OpenDataBio server, and
`token`, which is the access token used to authenticate your user (you can find it in the 
"Token" menu item, when using the web interface). While you can use the client with no 
authentication, note that some of the plants, samples and measurements may not be available
for anonymous access.

```r
cfg = odb_config(base_url = "http://opendatabio.ib.usp.br/opendatabio/api", token="YourToken")
```

More advanced configuration involves setting a specific API version, a custom User Agent, or
other HTTP headers, but this is not covered in this vignette.

The function `odb_test()` may be used to check if the connection was successful, and whether
your user was correctly identified:

```r
> odb_test(cfg)
$message
[1] "Success!"

$user
[1] "admin@example.org"
```
