#' Base functions
#'
#' These are some basic getter functions to interact with the API. See the full help on the package vignettes.
#' @examples
#' cfg = odb_config()
#' # Test request
#' odb_test()
#' # Gets some taxons
#' param = list(level=210, valid=TRUE, limit=5)
#' taxons = odb_get_taxons(param, cfg)
#' print(taxons)
#' \dontrun{
#' data = data.frame( 
#'   name = c("Euterpe oleracea", "Euterpe edulis"), 
#'   parent = "Euterpe"
#' )
#' common = list(level = "species")
#' odb_import_taxons(data, cfg, common)
#' }
#' @export
#' @param params named list, named vector or character string. Represents the parameters to be sent for the server, such as "valid=TRUE" to return only valid taxons. See \code{\link{odb_params}}
#' @param odb_cfg list. A configuration object, as generated by \code{\link{odb_config}}
#' @param data The data to be imported. The format is quite flexible, but normally a named \code{data.frame} is the best choice.
#' @param common Optional. A named list containing fields which are common to all imported data.
#' @param job_id numeric. A single job id 
#' @param simplify logical. Should the results be 'unlisted' before being returned?
#' @return odb_get methods usually return a \code{data.frame}, but that depends on the JSON response received from the server.
#' @import jsonlite
#' @rdname functions
odb_get_taxons <- function(params = list(), odb_cfg = odb_config(), simplify = TRUE) {
    response = odb_send_get(params, odb_cfg, "taxons")
    format_get_response(response, simplify)
}

#' @export 
#' @rdname functions
odb_import_taxons <- function(data, odb_cfg = odb_config(), common = list()) {
    response = odb_send_post(data, odb_cfg, "taxons", common)
    id = fromJSON(toJSON(content(response)))$userjob
    # Wait a second so that the job may start processing
    Sys.sleep(1)
    return (odb_get_jobs(list(id = id), odb_cfg))
}

#' @export
#' @rdname functions
odb_test <- function(odb_cfg = odb_config()) {
    response = odb_send_get(list(), odb_cfg, "/")
    inner_response = fromJSON(toJSON(content(response)))
    cat("Host:", inner_response$meta$full_url, "\n")
    cat("Versions: server", inner_response$meta$odb_version, "api", inner_response$meta$api_version, "\n")
    return (inner_response$data)
}

#' @export
#' @rdname functions
odb_get_jobs <- function(params = list(), odb_cfg = odb_config(), simplify = TRUE) {
    response = odb_send_get(params, odb_cfg, "jobs")
    format_get_response(response, simplify)
}

#' @export
#' @rdname functions
odb_get_log <- function(job_id, odb_cfg = odb_config()) {
	if (!is.numeric(job_id) | length(job_id) > 1) stop ("job_id must be a single number")
	job = odb_get_jobs(list(id = job_id, fields = "log"), odb_cfg)
	jsonlite::fromJSON(job$log[[1]])
}

#' @export
#' @rdname functions
odb_get_affected_ids <- function(job_id, odb_cfg = odb_config()) {
	if (!is.numeric(job_id) | length(job_id) > 1) stop ("job_id must be a single number")
	job = odb_get_jobs(list(id = job_id, fields = "affected_ids"), odb_cfg)
	jsonlite::fromJSON(job$affected_ids[[1]])
}

#' @export
#' @rdname functions
odb_get_locations <- function(params = list(), odb_cfg = odb_config(), simplify = TRUE) {
    response = odb_send_get(params, odb_cfg, "locations")
    format_get_response(response, simplify)
}

#' @export 
#' @rdname functions
odb_import_locations <- function(data, odb_cfg = odb_config(), common = list()) {
    if (class(data) != "data.frame") 
        stop ("Currently odb_import_taxons only accepts data.frame, please convert your data")
    cat("Sending ODB request (filesize = " , utils::object.size(data), ")\n", sep="")
    response = odb_send_post(data, odb_cfg, "locations", common)
    id = fromJSON(toJSON(content(response)))$userjob
    # Wait a second so that the job may start processing
    Sys.sleep(1)
    return (odb_get_jobs(list(id = id), odb_cfg))
} 

#' @export 
#' @rdname functions
odb_get_people <- function(params = list(), odb_cfg = odb_config(), simplify = TRUE) {
    response = odb_send_get(params, odb_cfg, "persons")
    format_get_response(response, simplify)
}	

#' @export 
#' @rdname functions
odb_import_people <- function(data, odb_cfg = odb_config(), common = list()) {
    if (class(data) != "data.frame") 
        stop ("Currently odb_import_people only accepts data.frame, please convert your data")
    cat("Sending ODB request (filesize = " , utils::object.size(data), ")\n", sep="")
    response = odb_send_post(data, odb_cfg, "persons", common)
    id = fromJSON(toJSON(content(response)))$userjob
    # Wait a second so that the job may start processing
    Sys.sleep(1)
    return (odb_get_jobs(list(id = id), odb_cfg))
}

#' @export 
#' @rdname functions
odb_get_plants <- function(params = list(), odb_cfg = odb_config(), simplify = TRUE) {
    response = odb_send_get(params, odb_cfg, "plants")
    format_get_response(response, simplify)
}	

#' @export 
#' @rdname functions
odb_import_plants <- function(data, odb_cfg = odb_config(), common = list()) {
    if (class(data) != "data.frame") 
        stop ("Currently odb_import_plants only accepts data.frame, please convert your data")
    cat("Sending ODB request (filesize = " , utils::object.size(data), ")\n", sep="")
    response = odb_send_post(data, odb_cfg, "plants", common)
    id = fromJSON(toJSON(content(response)))$userjob
    # Wait a second so that the job may start processing
    Sys.sleep(1)
    return (odb_get_jobs(list(id = id), odb_cfg))
}

#' @export
#' @rdname functions
odb_import_measurements <- function(data, odb_cfg = odb_config(), common = list()) {
    response = odb_send_post(data, odb_cfg, "measurements", common)
    id = fromJSON(toJSON(content(response)))$userjob
    # Wait a second so that the job may start processing
    Sys.sleep(1)
    return (odb_get_jobs(list(id = id), odb_cfg))
}
