#' Base functions
#'
#' These are some basic getter functions to interact with the API
#' @examples
#' cfg = odb_config()
#' # Test request
#' odb_test()
#' # Gets some taxons
#' param = list(level=210, valid=TRUE, limit=5)
#' taxons = odb_get_taxons(param, cfg)
#' print(taxons)
#' @export
#' @param params named list, named vector or character string. Represents the parameters to be sent for the server, such as "valid=TRUE" to return only valid taxons. See \code{\link{odb_params}}
#' @param odb_cfg list. A configuration object, as generated by \code{\link{odb_config}}
#' @param data The data to be imported. The format is quite flexible, but normally a named \code{data.frame} is the best choice.
#' @param job_id numeric. A single job id 
#' @return odb_get methods usually return a \code{data.frame}, but that depends on the JSON response received from the server.
#' @import jsonlite
#' @rdname functions
odb_get_taxons <- function(params = list(), odb_cfg = odb_config()) {
    response = odb_send_get(params, odb_cfg, "taxons")
    return (fromJSON(toJSON(content(response)))$data)
}

#' @export 
#' @rdname functions
odb_import_taxons <- function(data, odb_cfg = odb_config()) {
    response = odb_send_post(data, odb_cfg, "taxons")
    id = fromJSON(toJSON(content(response)))$userjob
    # Wait a second so that the job may start processing
    Sys.sleep(1)
    return (odb_get_jobs(list(id = id), odb_cfg))
}

#' @export
#' @rdname functions
odb_test <- function(odb_cfg = odb_config()) {
    response = odb_send_get(list(), odb_cfg, "/")
    return (fromJSON(toJSON(content(response)))$data)
}

#' @export
#' @rdname functions
odb_get_jobs <- function(params = list(), odb_cfg = odb_config()) {
    response = odb_send_get(params, odb_cfg, "jobs")
    return(fromJSON(toJSON(content(response)))$data)
}

#' @export
#' @rdname functions
odb_get_log <- function(job_id, odb_cfg = odb_config()) {
	if (!is.numeric(job_id) | length(job_id) > 1) stop ("job_id must be a single number")
	job = odb_get_jobs(list(id = job_id, fields = "log"), odb_cfg)
	jsonlite::fromJSON(job$log[[1]])
}

#' @export
#' @rdname functions
odb_get_affected_ids <- function(job_id, odb_cfg = odb_config()) {
	if (!is.numeric(job_id) | length(job_id) > 1) stop ("job_id must be a single number")
	job = odb_get_jobs(list(id = job_id, fields = "affected_ids"), odb_cfg)
	jsonlite::fromJSON(job$affected_ids[[1]])
}

#' @export
#' @rdname functions
odb_get_locations <- function(params = list(), odb_cfg = odb_config()) {
    response = odb_send_get(params, odb_cfg, "locations")
    return(fromJSON(toJSON(content(response)))$data)
}

#' @export 
#' @rdname functions
odb_import_locations <- function(data, odb_cfg = odb_config()) {
    if (class(data) != "data.frame") 
        stop ("Currently odb_import_taxons only accepts data.frame, please convert your data")
    cat("Sending ODB request (filesize = " , utils::object.size(data), ")\n", sep="")
    response = odb_send_post(data, odb_cfg, "locations")
    id = fromJSON(toJSON(content(response)))$userjob
    # Wait a second so that the job may start processing
    Sys.sleep(1)
    return (odb_get_jobs(list(id = id), odb_cfg))
} 

#' @export 
#' @rdname functions
odb_get_people <- function(params = list(), odb_cfg = odb_config()) {
    response = odb_send_get(params, odb_cfg, "persons")
    return(fromJSON(toJSON(content(response)))$data)
}	

#' @export 
#' @rdname functions
odb_import_people <- function(data, odb_cfg = odb_config()) {
    if (class(data) != "data.frame") 
        stop ("Currently odb_import_people only accepts data.frame, please convert your data")
    cat("Sending ODB request (filesize = " , utils::object.size(data), ")\n", sep="")
    response = odb_send_post(data, odb_cfg, "persons")
    id = fromJSON(toJSON(content(response)))$userjob
    # Wait a second so that the job may start processing
    Sys.sleep(1)
    return (odb_get_jobs(list(id = id), odb_cfg))
}

#' @export 
#' @rdname functions
odb_get_plants <- function(params = list(), odb_cfg = odb_config()) {
    response = odb_send_get(params, odb_cfg, "plants")
    return(fromJSON(toJSON(content(response)))$data)
}	

#' @export 
#' @rdname functions
odb_import_plants <- function(data, odb_cfg = odb_config()) {
    if (class(data) != "data.frame") 
        stop ("Currently odb_import_plants only accepts data.frame, please convert your data")
    cat("Sending ODB request (filesize = " , utils::object.size(data), ")\n", sep="")
    response = odb_send_post(data, odb_cfg, "plants")
    id = fromJSON(toJSON(content(response)))$userjob
    # Wait a second so that the job may start processing
    Sys.sleep(1)
    return (odb_get_jobs(list(id = id), odb_cfg))
}
